In [1]:
import pandas as pd

In [2]:
pd.read_csv('./Data/Gross_Domestic_Product_All_India_and_Madhya_Pradesh.csv')

,Year,Comparative Figures (Crore Rs.) All-India At Current Prices,Comparative Figures (Crore Rs.) All-India At Constant Prices,Comparative Figures (Crore Rs.) Madhya Pradesh At Current Prices,Comparative Figures (Crore Rs.) Madhya Pradesh At Constant Prices,% Increase Over Previous Year All-India At Current Prices,% Increase Over Previous Year All-India At Constant Prices,% Increase Over Previous Year Madhya Pradesh At Current Prices,% Increase Over Previous Year Madhya Pradesh At Constant Prices
0,2004-05,2971464,2971464,112927,112927,NaN,NaN,NaN,NaN
1,2005-06,3390503,3253073,124276,118919,14.10,9.48,10.05,5.31
2,2006-07,3953276,3564364,144577,129896,16.60,9.57,16.34,9.23
3,2007-08,4582086,3896636,161479,135986,15.91,9.32,11.69,4.69
4,2008-09,5303567,4158676,197276,152946,15.75,6.72,22.17,12.47
5,2009-10,6108903,4516071,227557,167564,15.18,8.59,15.35,9.56
6,2010-11,7248860,4918533,263396,178144,18.66,8.91,15.75,6.31
7,2011-12 (P),8391691,5247530,311670,195409,15.77,6.69,18.33,9.69
8,2012-13 (Q),9388876,5482111,372171,214741,11.88,4.47,19.41,9.89
9,2012-13 (A),10539605,5748564,450900,238526,12.26,4.86,21.15,11.08